<?php

use  Drupal\Core\Form\FormStateInterface;
use Drupal\nextcloud\NextcloudApiWrapper\Wrapper;

use Drupal\nextcloud\NextcloudApiWrapper\UsersClient;


function nextcloud_form_alter(&$form, FormStateInterface $form_state, $form_id)
{
    if ($form_id === 'user_register_form') {
        $form['actions']['submit']['#submit'][] = 'nextcloud_submit';
    }
}

function nextcloud_submit($form, FormStateInterface $form_state)
{

    $name = $form_state->getValue('name');
    $pass = $form_state->getValue('pass');
	dsm("hello");
	
    /*$basePath = 'https://213.233.177.241/';
    $username = 'nextcloud';
    $password = 'nextcloud';

    $wrapper = Wrapper::build($basePath, $username, $password);
    $wrapper->getUsersClient()->addUser($name, $pass);
    $wrapper->getUsersClient()->addUserToGroup($name, 'groupname');*/
}



?>